# This is used with the label workflow which
# will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# For more information, see:
# https://github.com/actions/labeler

# Add 'approved' label when a PR containing files from src/**/* is approved.
'approved':
  - src/**/*

