name: Add Label on PR Approval

on:
  pull_request_review:
    types:
      - submitted

jobs:
  add_label:
    runs-on: ubuntu-latest # the common choice of the envirionment running github actions.
    steps:
      - name: Check if PR is approved
        id: check_approval
        run: |
          if [[ "${{ github.event.review.state }}" == "approved" ]]; then
            echo "APPROVED"
          else
            echo "NOT_APPROVED"
          fi

      - name: Add Label to Approved PR
        if: steps.check_approval.outputs.check_approval == 'APPROVED'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["approved"]
            })
