name: "Pull Request Labeler"
on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    permissions:
      contents: read
      pull-requests: write
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
