name: "Run unit testing on opening a PR"

on:
  pull_request:
    branches:
      - dev
      - release
      - master

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'

      # - name: Install dependencies
      #   run: npm install

      # - name: Run tests
      #   run: |
      #     result=$(npm test)
      #     echo $result

      - name: Dismiss approved pr
        if: always()  # This step runs regardless of the test results
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pull_number = context.payload.pull_request.number;

            const reviews = await github.pulls.listReviews({ owner, repo, pull_number });
            console.log('reviews', reviews)

      # - name: Set PR status
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      #   if: always()  # This step runs regardless of the test results
      #   continue-on-error: true
      #   run: |
      #     if [[ $GITHUB_REF =~ /pull/([0-9]+)/ ]]; then
      #       echo "Unit testing result: ${{ job.status }}"
      #       PR_NUMBER="${BASH_REMATCH[1]}"
      #       if [ "${{ job.status }}" = 'success' ]; then
      #         gh pr review "$PR_NUMBER" --comment --body "Unit testing OK, ready to review"
      #       else
      #         gh pr review "$PR_NUMBER" --request-changes --body "Unit testing NOK, please fix it."
      #       fi
      #     fi