name: "Run unit testing on opening a PR"
on:
  pull_request:
    branches:
      - dev
      - release
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Set PR status
        if: always()  # This step runs regardless of the test results
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            gh pr review --comment "Unit testing failed, ready for review."
          else
            gh pr review --comment "Unit testing failed!"
          fi
